languages:
  Ruby: false
  JavaScript: true
  PHP: false
  Python: false
exclude_paths:
  - "demo/*"
  - "karma.config.js"
  - "webpack.config.js"
  - "test/*"
  - "push-state-tree.js"
  - "push-state-tree.min.js"
